### ISSUE TITLE
The Reward Get From Soulsgym

### ISSUE THREAD

**Issue by ListentoMe0112** [amacati/SoulsAI#2]
Thanks for providing such wonderful framework!
But there is something bother me.
In your ReadMe, the figure of Episode/Reward seem to be boundaried between -200 to 200 which is not correspond to the soulsgym?
<img width="908" alt="grafana_2" src="https://github.com/amacati/SoulsAI/assets/66709955/f003c1ae-7604-495f-90f4-8d00aaf8c657">
In Soulsgym, we can only get positive reward from boss's hp reduction divided by boss's max hp.
```python
# In SoulsGym 1.1.0
boss_reward = ((game_state.boss_hp - next_game_state.boss_hp) / game_state.boss_max_hp)
```
This cann't be transform to [-200, 200].
Does this have any tricks?
Or something like reward *= 200?

**Comment by amacati** [comment]
Hi, sorry for the confusion. This is from an old SoulsGym version where the reward was scaled from approximately -200 to 200. The newer version is scaled to approximately -1 to 1. While the scaling is arbitrary, it can affect the learning hyperparameters, so I decided to standardize it around the `[-1, 1]` interval.

You can still find the old reward function, e.g. at [this commit](https://github.com/amacati/SoulsGym/blob/ba7fc6ad53f01733e3d2ddaf8d7ded8bb9907ecf/soulsgym/envs/darksouls3/iudex_env.py#L269).

I'm working on some major improvements to SoulsAI. Once those are merged, I will hopefully have some time to fix the docs.

**Comment by ListentoMe0112** [comment]
Thanks for reply~
